"""Static data for the Structure Browser: prebuilt molecules and category order."""

STRUCTURE_CATEGORY_ORDER = [
    'Functional Groups', 'Alkanes', 'Alkenes && Alkynes', 'Aromatics', 'Heterocycles',
    'Alcohols && Ethers', 'Carbonyls, Acids && Esters', 'Amines && Nitrogen Compounds',
    'Halides', 'Sulfur && Phosphorus', 'Amino Acids', 'Sugars', 'Common Solvents',
    'Pharmaceuticals', 'Vitamins', 'Nucleobases', 'Polymer Monomers',
    'Inorganic && Small Molecules', 'Fatty Acids && Lipids', 'Terpenes && Natural Products',
    'Steroids', 'Dyes && Pigments', 'Macrocycles && Crown Ethers', 'Esters && Flavor Compounds',
]

PREBUILT_STRUCTURES = [
    {'name': 'Methyl', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'C', 'elements': {'C': 1, 'H': 4}},
    {'name': 'Ethyl', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CC', 'elements': {'C': 2, 'H': 6}},
    {'name': 'Hydroxyl (Methanol)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CO',
     'elements': {'C': 1, 'H': 4, 'O': 1}},
    {'name': 'Carboxylic Acid (Acetic Acid)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CC(=O)O',
     'elements': {'C': 2, 'H': 4, 'O': 2}},
    {'name': 'Aldehyde (Acetaldehyde)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CC=O',
     'elements': {'C': 2, 'H': 4, 'O': 1}},
    {'name': 'Amine (Methylamine)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CN',
     'elements': {'C': 1, 'H': 5, 'N': 1}},
    {'name': 'Nitro (Nitromethane)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'C[N+](=O)[O-]',
     'elements': {'C': 1, 'H': 3, 'N': 1, 'O': 2}},
    {'name': 'Nitrile (Acetonitrile)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CC#N',
     'elements': {'C': 2, 'H': 3, 'N': 1}},
    {'name': 'Fluoromethane', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CF',
     'elements': {'C': 1, 'F': 1, 'H': 3}},
    {'name': 'Chloromethane', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CCl',
     'elements': {'C': 1, 'Cl': 1, 'H': 3}},
    {'name': 'Bromomethane', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CBr',
     'elements': {'Br': 1, 'C': 1, 'H': 3}},
    {'name': 'Iodomethane', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CI',
     'elements': {'C': 1, 'H': 3, 'I': 1}},
    {'name': 'Ester (Methyl Acetate)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'COC(C)=O',
     'elements': {'C': 3, 'H': 6, 'O': 2}},
    {'name': 'Ketone (Acetone)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CC(C)=O',
     'elements': {'C': 3, 'H': 6, 'O': 1}},
    {'name': 'Ether (Dimethyl Ether)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'COC',
     'elements': {'C': 2, 'H': 6, 'O': 1}},
    {'name': 'Amide (Acetamide)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CC(N)=O',
     'elements': {'C': 2, 'H': 5, 'N': 1, 'O': 1}},
    {'name': 'Thiol (Methanethiol)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CS',
     'elements': {'C': 1, 'H': 4, 'S': 1}},
    {'name': 'Sulfonic Acid', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CS(=O)(=O)O',
     'elements': {'C': 1, 'H': 4, 'O': 3, 'S': 1}},
    {'name': 'Isocyanate', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'CN=C=O',
     'elements': {'C': 2, 'H': 3, 'N': 1, 'O': 1}},
    {'name': 'Epoxide (Ethylene Oxide)', 'category': STRUCTURE_CATEGORY_ORDER[0], 'smiles': 'C1CO1',
     'elements': {'C': 2, 'H': 4, 'O': 1}},
    {'name': 'Propane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCC', 'elements': {'C': 3, 'H': 8}},
    {'name': 'n-Butane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCC', 'elements': {'C': 4, 'H': 10}},
    {'name': 'Isobutane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CC(C)C', 'elements': {'C': 4, 'H': 10}},
    {'name': 'n-Pentane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCC', 'elements': {'C': 5, 'H': 12}},
    {'name': 'Isopentane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCC(C)C', 'elements': {'C': 5, 'H': 12}},
    {'name': 'Neopentane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CC(C)(C)C',
     'elements': {'C': 5, 'H': 12}},
    {'name': 'n-Hexane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCCC', 'elements': {'C': 6, 'H': 14}},
    {'name': '2-Methylpentane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCC(C)C',
     'elements': {'C': 6, 'H': 14}},
    {'name': '3-Methylpentane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCC(C)CC',
     'elements': {'C': 6, 'H': 14}},
    {'name': '2,2-Dimethylbutane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCC(C)(C)C',
     'elements': {'C': 6, 'H': 14}},
    {'name': 'n-Heptane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCCCC', 'elements': {'C': 7, 'H': 16}},
    {'name': 'n-Octane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCCCCC', 'elements': {'C': 8, 'H': 18}},
    {'name': 'Isooctane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CC(C)CC(C)(C)C',
     'elements': {'C': 8, 'H': 18}},
    {'name': 'n-Nonane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCCCCCC', 'elements': {'C': 9, 'H': 20}},
    {'name': 'n-Decane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCCCCCCC',
     'elements': {'C': 10, 'H': 22}},
    {'name': 'n-Dodecane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCCCCCCCCC',
     'elements': {'C': 12, 'H': 26}},
    {'name': 'Cyclopropane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CC1', 'elements': {'C': 3, 'H': 6}},
    {'name': 'Cyclobutane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CCC1', 'elements': {'C': 4, 'H': 8}},
    {'name': 'Cyclopentane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CCCC1',
     'elements': {'C': 5, 'H': 10}},
    {'name': 'Cyclohexane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CCCCC1',
     'elements': {'C': 6, 'H': 12}},
    {'name': 'Cycloheptane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CCCCCC1',
     'elements': {'C': 7, 'H': 14}},
    {'name': 'Cyclooctane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CCCCCCC1',
     'elements': {'C': 8, 'H': 16}},
    {'name': 'Methylcyclohexane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CC1CCCCC1',
     'elements': {'C': 7, 'H': 14}},
    {'name': 'Decalin', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CCC2CCCCC2C1',
     'elements': {'C': 10, 'H': 18}},
    {'name': 'Adamantane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CC2CC3CC1CC(C2)C3',
     'elements': {'C': 11, 'H': 18}},
    {'name': 'Norbornane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CC2CCC1C2',
     'elements': {'C': 7, 'H': 12}},
    {'name': 'Ethylene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=C', 'elements': {'C': 2, 'H': 4}},
    {'name': 'Propylene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CC', 'elements': {'C': 3, 'H': 6}},
    {'name': '1-Butene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CCC', 'elements': {'C': 4, 'H': 8}},
    {'name': 'cis-2-Butene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C/C=C\\C',
     'elements': {'C': 4, 'H': 8}},
    {'name': 'trans-2-Butene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C/C=C/C',
     'elements': {'C': 4, 'H': 8}},
    {'name': 'Isobutylene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=C(C)C', 'elements': {'C': 4, 'H': 8}},
    {'name': '1-Pentene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CCCC', 'elements': {'C': 5, 'H': 10}},
    {'name': '1-Hexene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CCCCC', 'elements': {'C': 6, 'H': 12}},
    {'name': '1,3-Butadiene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CC=C',
     'elements': {'C': 4, 'H': 6}},
    {'name': 'Isoprene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CC(=C)C', 'elements': {'C': 5, 'H': 8}},
    {'name': 'Cyclopentene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C1=CCCC1',
     'elements': {'C': 5, 'H': 8}},
    {'name': 'Cyclohexene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C1=CCCCC1',
     'elements': {'C': 6, 'H': 10}},
    {'name': '1,3-Cyclohexadiene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C1=CCCC=C1',
     'elements': {'C': 6, 'H': 8}},
    {'name': '1,3,5-Cyclooctatriene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C1=CC=CCCC=C1',
     'elements': {'C': 8, 'H': 10}},
    {'name': 'Acetylene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C#C', 'elements': {'C': 2, 'H': 2}},
    {'name': 'Propyne', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C#CC', 'elements': {'C': 3, 'H': 4}},
    {'name': '1-Butyne', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C#CCC', 'elements': {'C': 4, 'H': 6}},
    {'name': '2-Butyne', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'CC#CC', 'elements': {'C': 4, 'H': 6}},
    {'name': 'Benzene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'c1ccccc1', 'elements': {'C': 6, 'H': 6}},
    {'name': 'Toluene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Cc1ccccc1', 'elements': {'C': 7, 'H': 8}},
    {'name': 'o-Xylene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Cc1ccccc1C',
     'elements': {'C': 8, 'H': 10}},
    {'name': 'm-Xylene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Cc1cccc(C)c1',
     'elements': {'C': 8, 'H': 10}},
    {'name': 'p-Xylene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Cc1ccc(C)cc1',
     'elements': {'C': 8, 'H': 10}},
    {'name': 'Ethylbenzene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'CCc1ccccc1',
     'elements': {'C': 8, 'H': 10}},
    {'name': 'Styrene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'C=Cc1ccccc1', 'elements': {'C': 8, 'H': 8}},
    {'name': 'Cumene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'CC(C)c1ccccc1',
     'elements': {'C': 9, 'H': 12}},
    {'name': 'Naphthalene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'c1ccc2ccccc2c1',
     'elements': {'C': 10, 'H': 8}},
    {'name': 'Anthracene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'c1ccc2cc3ccccc3cc2c1',
     'elements': {'C': 14, 'H': 10}},
    {'name': 'Phenanthrene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'c1ccc2c(c1)ccc1ccccc12',
     'elements': {'C': 14, 'H': 10}},
    {'name': 'Pyrene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'c1cc2ccc3cccc4ccc(c1)c2c34',
     'elements': {'C': 16, 'H': 10}},
    {'name': 'Biphenyl', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'c1ccc(-c2ccccc2)cc1',
     'elements': {'C': 12, 'H': 10}},
    {'name': 'Phenol', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Oc1ccccc1',
     'elements': {'C': 6, 'H': 6, 'O': 1}},
    {'name': 'Aniline', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Nc1ccccc1',
     'elements': {'C': 6, 'H': 7, 'N': 1}},
    {'name': 'Benzaldehyde', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'O=Cc1ccccc1',
     'elements': {'C': 7, 'H': 6, 'O': 1}},
    {'name': 'Benzoic Acid', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'O=C(O)c1ccccc1',
     'elements': {'C': 7, 'H': 6, 'O': 2}},
    {'name': 'Benzonitrile', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'N#Cc1ccccc1',
     'elements': {'C': 7, 'H': 5, 'N': 1}},
    {'name': 'Nitrobenzene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'O=[N+]([O-])c1ccccc1',
     'elements': {'C': 6, 'H': 5, 'N': 1, 'O': 2}},
    {'name': 'Chlorobenzene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Clc1ccccc1',
     'elements': {'C': 6, 'Cl': 1, 'H': 5}},
    {'name': 'Bromobenzene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Brc1ccccc1',
     'elements': {'Br': 1, 'C': 6, 'H': 5}},
    {'name': 'Fluorobenzene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Fc1ccccc1',
     'elements': {'C': 6, 'F': 1, 'H': 5}},
    {'name': 'Anisole', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'COc1ccccc1',
     'elements': {'C': 7, 'H': 8, 'O': 1}},
    {'name': 'Catechol', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Oc1ccccc1O',
     'elements': {'C': 6, 'H': 6, 'O': 2}},
    {'name': 'Resorcinol', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Oc1cccc(O)c1',
     'elements': {'C': 6, 'H': 6, 'O': 2}},
    {'name': 'Hydroquinone', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Oc1ccc(O)cc1',
     'elements': {'C': 6, 'H': 6, 'O': 2}},
    {'name': 'Salicylic Acid', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'O=C(O)c1ccccc1O',
     'elements': {'C': 7, 'H': 6, 'O': 3}},
    {'name': 'Acetophenone', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'CC(=O)c1ccccc1',
     'elements': {'C': 8, 'H': 8, 'O': 1}},
    {'name': 'Cinnamaldehyde', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'O=C/C=C/c1ccccc1',
     'elements': {'C': 9, 'H': 8, 'O': 1}},
    {'name': 'Benzyl Alcohol', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'OCc1ccccc1',
     'elements': {'C': 7, 'H': 8, 'O': 1}},
    {'name': 'p-Cresol', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Cc1ccc(O)cc1',
     'elements': {'C': 7, 'H': 8, 'O': 1}},
    {'name': 'Indene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'C1=Cc2ccccc2C1',
     'elements': {'C': 9, 'H': 8}},
    {'name': 'Fluorene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'c1ccc2c(c1)Cc1ccccc1-2',
     'elements': {'C': 13, 'H': 10}},
    {'name': 'Pyridine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccncc1',
     'elements': {'C': 5, 'H': 5, 'N': 1}},
    {'name': 'Pyrrole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1cc[nH]c1',
     'elements': {'C': 4, 'H': 5, 'N': 1}},
    {'name': 'Furan', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccoc1',
     'elements': {'C': 4, 'H': 4, 'O': 1}},
    {'name': 'Thiophene', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccsc1',
     'elements': {'C': 4, 'H': 4, 'S': 1}},
    {'name': 'Imidazole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1c[nH]cn1',
     'elements': {'C': 3, 'H': 4, 'N': 2}},
    {'name': 'Pyrazole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1cn[nH]c1',
     'elements': {'C': 3, 'H': 4, 'N': 2}},
    {'name': 'Oxazole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1cocn1',
     'elements': {'C': 3, 'H': 3, 'N': 1, 'O': 1}},
    {'name': 'Thiazole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1cscn1',
     'elements': {'C': 3, 'H': 3, 'N': 1, 'S': 1}},
    {'name': 'Pyrimidine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1cncnc1',
     'elements': {'C': 4, 'H': 4, 'N': 2}},
    {'name': 'Pyridazine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccnnc1',
     'elements': {'C': 4, 'H': 4, 'N': 2}},
    {'name': 'Indole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2[nH]ccc2c1',
     'elements': {'C': 8, 'H': 7, 'N': 1}},
    {'name': 'Quinoline', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2ncccc2c1',
     'elements': {'C': 9, 'H': 7, 'N': 1}},
    {'name': 'Isoquinoline', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2cnccc2c1',
     'elements': {'C': 9, 'H': 7, 'N': 1}},
    {'name': 'Purine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ncc2[nH]cnc2n1',
     'elements': {'C': 5, 'H': 4, 'N': 4}},
    {'name': 'Benzimidazole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2[nH]cnc2c1',
     'elements': {'C': 7, 'H': 6, 'N': 2}},
    {'name': 'Benzofuran', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2occc2c1',
     'elements': {'C': 8, 'H': 6, 'O': 1}},
    {'name': 'Benzothiophene', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2sccc2c1',
     'elements': {'C': 8, 'H': 6, 'S': 1}},
    {'name': 'Piperidine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'C1CCNCC1',
     'elements': {'C': 5, 'H': 11, 'N': 1}},
    {'name': 'Piperazine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'C1CNCCN1',
     'elements': {'C': 4, 'H': 10, 'N': 2}},
    {'name': 'Morpholine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'C1COCCN1',
     'elements': {'C': 4, 'H': 9, 'N': 1, 'O': 1}},
    {'name': 'Tetrahydrofuran', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'C1CCOC1',
     'elements': {'C': 4, 'H': 8, 'O': 1}},
    {'name': 'Tetrahydropyran', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'C1CCOCC1',
     'elements': {'C': 5, 'H': 10, 'O': 1}},
    {'name': 'Dioxane', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'C1COCCO1',
     'elements': {'C': 4, 'H': 8, 'O': 2}},
    {'name': 'Pyrrolidine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'C1CCNC1',
     'elements': {'C': 4, 'H': 9, 'N': 1}},
    {'name': 'Caffeine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'Cn1c(=O)c2c(ncn2C)n(C)c1=O',
     'elements': {'C': 8, 'H': 10, 'N': 4, 'O': 2}},
    {'name': 'Indolizine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccn2cccc2c1',
     'elements': {'C': 8, 'H': 7, 'N': 1}},
    {'name': 'Ethanol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'CCO', 'elements': {'C': 2, 'H': 6, 'O': 1}},
    {'name': '1-Propanol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'CCCO',
     'elements': {'C': 3, 'H': 8, 'O': 1}},
    {'name': 'Isopropanol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'CC(C)O',
     'elements': {'C': 3, 'H': 8, 'O': 1}},
    {'name': '1-Butanol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'CCCCO',
     'elements': {'C': 4, 'H': 10, 'O': 1}},
    {'name': 'tert-Butanol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'CC(C)(C)O',
     'elements': {'C': 4, 'H': 10, 'O': 1}},
    {'name': 'Ethylene Glycol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'OCCO',
     'elements': {'C': 2, 'H': 6, 'O': 2}},
    {'name': 'Propylene Glycol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'CC(O)CO',
     'elements': {'C': 3, 'H': 8, 'O': 2}},
    {'name': 'Glycerol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'OCC(O)CO',
     'elements': {'C': 3, 'H': 8, 'O': 3}},
    {'name': 'Diethyl Ether', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'CCOCC',
     'elements': {'C': 4, 'H': 10, 'O': 1}},
    {'name': 'Cyclohexanol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'OC1CCCCC1',
     'elements': {'C': 6, 'H': 12, 'O': 1}},
    {'name': '1,4-Butanediol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'OCCCCO',
     'elements': {'C': 4, 'H': 10, 'O': 2}},
    {'name': 'Pentaerythritol', 'category': STRUCTURE_CATEGORY_ORDER[5], 'smiles': 'OCC(CO)(CO)CO',
     'elements': {'C': 5, 'H': 12, 'O': 4}},
    {'name': 'Formaldehyde', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'C=O',
     'elements': {'C': 1, 'H': 2, 'O': 1}},
    {'name': 'Propionaldehyde', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'CCC=O',
     'elements': {'C': 3, 'H': 6, 'O': 1}},
    {'name': 'Methyl Ethyl Ketone', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'CCC(C)=O',
     'elements': {'C': 4, 'H': 8, 'O': 1}},
    {'name': 'Cyclohexanone', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'O=C1CCCCC1',
     'elements': {'C': 6, 'H': 10, 'O': 1}},
    {'name': 'Formic Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'O=CO',
     'elements': {'C': 1, 'H': 2, 'O': 2}},
    {'name': 'Propionic Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'CCC(=O)O',
     'elements': {'C': 3, 'H': 6, 'O': 2}},
    {'name': 'Butyric Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'CCCC(=O)O',
     'elements': {'C': 4, 'H': 8, 'O': 2}},
    {'name': 'Oxalic Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'O=C(O)C(=O)O',
     'elements': {'C': 2, 'H': 2, 'O': 4}},
    {'name': 'Malonic Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'O=C(O)CC(=O)O',
     'elements': {'C': 3, 'H': 4, 'O': 4}},
    {'name': 'Succinic Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'O=C(O)CCC(=O)O',
     'elements': {'C': 4, 'H': 6, 'O': 4}},
    {'name': 'Citric Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'O=C(O)CC(O)(CC(=O)O)C(=O)O',
     'elements': {'C': 6, 'H': 8, 'O': 7}},
    {'name': 'Lactic Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'CC(O)C(=O)O',
     'elements': {'C': 3, 'H': 6, 'O': 3}},
    {'name': 'Pyruvic Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'CC(=O)C(=O)O',
     'elements': {'C': 3, 'H': 4, 'O': 3}},
    {'name': 'Acrylic Acid', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'C=CC(=O)O',
     'elements': {'C': 3, 'H': 4, 'O': 2}},
    {'name': 'Ethyl Acetate', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'CCOC(C)=O',
     'elements': {'C': 4, 'H': 8, 'O': 2}},
    {'name': 'Methyl Methacrylate', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'C=C(C)C(=O)OC',
     'elements': {'C': 5, 'H': 8, 'O': 2}},
    {'name': 'Vinyl Acetate', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'C=COC(C)=O',
     'elements': {'C': 4, 'H': 6, 'O': 2}},
    {'name': 'Acetic Anhydride', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'CC(=O)OC(C)=O',
     'elements': {'C': 4, 'H': 6, 'O': 3}},
    {'name': 'Acetyl Chloride', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'CC(=O)Cl',
     'elements': {'C': 2, 'Cl': 1, 'H': 3, 'O': 1}},
    {'name': 'Phosgene', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'O=C(Cl)Cl',
     'elements': {'C': 1, 'Cl': 2, 'O': 1}},
    {'name': 'Urea', 'category': STRUCTURE_CATEGORY_ORDER[6], 'smiles': 'NC(N)=O',
     'elements': {'C': 1, 'H': 4, 'N': 2, 'O': 1}},
    {'name': 'Dimethylamine', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'CNC',
     'elements': {'C': 2, 'H': 7, 'N': 1}},
    {'name': 'Trimethylamine', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'CN(C)C',
     'elements': {'C': 3, 'H': 9, 'N': 1}},
    {'name': 'Ethylamine', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'CCN',
     'elements': {'C': 2, 'H': 7, 'N': 1}},
    {'name': 'Ethylenediamine', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'NCCN',
     'elements': {'C': 2, 'H': 8, 'N': 2}},
    {'name': 'Hexamethylenediamine', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'NCCCCCCN',
     'elements': {'C': 6, 'H': 16, 'N': 2}},
    {'name': 'Hydrazine', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'NN', 'elements': {'H': 4, 'N': 2}},
    {'name': 'Hydroxylamine', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'NO',
     'elements': {'H': 3, 'N': 1, 'O': 1}},
    {'name': 'Acrylonitrile', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'C=CC#N',
     'elements': {'C': 3, 'H': 3, 'N': 1}},
    {'name': 'N,N-Dimethylformamide', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'CN(C)C=O',
     'elements': {'C': 3, 'H': 7, 'N': 1, 'O': 1}},
    {'name': 'Nicotine', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'CN1CCCC1c1cccnc1',
     'elements': {'C': 10, 'H': 14, 'N': 2}},
    {'name': 'Guanidine', 'category': STRUCTURE_CATEGORY_ORDER[7], 'smiles': 'N=C(N)N',
     'elements': {'C': 1, 'H': 5, 'N': 3}},
    {'name': 'Dichloromethane', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'ClCCl',
     'elements': {'C': 1, 'Cl': 2, 'H': 2}},
    {'name': 'Chloroform', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'ClC(Cl)Cl',
     'elements': {'C': 1, 'Cl': 3, 'H': 1}},
    {'name': 'Carbon Tetrachloride', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'ClC(Cl)(Cl)Cl',
     'elements': {'C': 1, 'Cl': 4}},
    {'name': '1,2-Dichloroethane', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'ClCCCl',
     'elements': {'C': 2, 'Cl': 2, 'H': 4}},
    {'name': 'Vinyl Chloride', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'C=CCl',
     'elements': {'C': 2, 'Cl': 1, 'H': 3}},
    {'name': 'Bromoethane', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'CCBr',
     'elements': {'Br': 1, 'C': 2, 'H': 5}},
    {'name': 'Carbon Tetrafluoride', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'FC(F)(F)F',
     'elements': {'C': 1, 'F': 4}},
    {'name': 'Freon-12', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'FC(F)(Cl)Cl',
     'elements': {'C': 1, 'Cl': 2, 'F': 2}},
    {'name': 'Hexafluoroethane', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'FC(F)(F)C(F)(F)F',
     'elements': {'C': 2, 'F': 6}},
    {'name': 'Iodoform', 'category': STRUCTURE_CATEGORY_ORDER[8], 'smiles': 'IC(I)I',
     'elements': {'C': 1, 'H': 1, 'I': 3}},
    {'name': 'Hydrogen Sulfide', 'category': STRUCTURE_CATEGORY_ORDER[9], 'smiles': 'S', 'elements': {'H': 2, 'S': 1}},
    {'name': 'Dimethyl Sulfide', 'category': STRUCTURE_CATEGORY_ORDER[9], 'smiles': 'CSC',
     'elements': {'C': 2, 'H': 6, 'S': 1}},
    {'name': 'Dimethyl Sulfoxide', 'category': STRUCTURE_CATEGORY_ORDER[9], 'smiles': 'CS(C)=O',
     'elements': {'C': 2, 'H': 6, 'O': 1, 'S': 1}},
    {'name': 'Dimethyl Sulfone', 'category': STRUCTURE_CATEGORY_ORDER[9], 'smiles': 'CS(C)(=O)=O',
     'elements': {'C': 2, 'H': 6, 'O': 2, 'S': 1}},
    {'name': 'Sulfuric Acid Ester (Dimethyl Sulfate)', 'category': STRUCTURE_CATEGORY_ORDER[9],
     'smiles': 'COS(=O)(=O)OC',
     'elements': {'C': 2, 'H': 6, 'O': 4, 'S': 1}},
    {'name': 'Trimethyl Phosphate', 'category': STRUCTURE_CATEGORY_ORDER[9], 'smiles': 'COP(=O)(OC)OC',
     'elements': {'C': 3, 'H': 9, 'O': 4, 'P': 1}},
    {'name': 'Phosphine', 'category': STRUCTURE_CATEGORY_ORDER[9], 'smiles': 'P', 'elements': {'H': 3, 'P': 1}},
    {'name': 'Triphenylphosphine', 'category': STRUCTURE_CATEGORY_ORDER[9], 'smiles': 'c1ccc(P(c2ccccc2)c2ccccc2)cc1',
     'elements': {'C': 18, 'H': 15, 'P': 1}},
    {'name': 'Glycine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NCC(=O)O',
     'elements': {'C': 2, 'H': 5, 'N': 1, 'O': 2}},
    {'name': 'Alanine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'CC(N)C(=O)O',
     'elements': {'C': 3, 'H': 7, 'N': 1, 'O': 2}},
    {'name': 'Serine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(CO)C(=O)O',
     'elements': {'C': 3, 'H': 7, 'N': 1, 'O': 3}},
    {'name': 'Cysteine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(CS)C(=O)O',
     'elements': {'C': 3, 'H': 7, 'N': 1, 'O': 2, 'S': 1}},
    {'name': 'Valine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'CC(C)C(N)C(=O)O',
     'elements': {'C': 5, 'H': 11, 'N': 1, 'O': 2}},
    {'name': 'Leucine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'CC(C)CC(N)C(=O)O',
     'elements': {'C': 6, 'H': 13, 'N': 1, 'O': 2}},
    {'name': 'Isoleucine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'CCC(C)C(N)C(=O)O',
     'elements': {'C': 6, 'H': 13, 'N': 1, 'O': 2}},
    {'name': 'Proline', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'O=C(O)C1CCCN1',
     'elements': {'C': 5, 'H': 9, 'N': 1, 'O': 2}},
    {'name': 'Threonine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'CC(O)C(N)C(=O)O',
     'elements': {'C': 4, 'H': 9, 'N': 1, 'O': 3}},
    {'name': 'Aspartic Acid', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(CC(=O)O)C(=O)O',
     'elements': {'C': 4, 'H': 7, 'N': 1, 'O': 4}},
    {'name': 'Glutamic Acid', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(CCC(=O)O)C(=O)O',
     'elements': {'C': 5, 'H': 9, 'N': 1, 'O': 4}},
    {'name': 'Asparagine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(=O)CC(N)C(=O)O',
     'elements': {'C': 4, 'H': 8, 'N': 2, 'O': 3}},
    {'name': 'Glutamine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(=O)CCC(N)C(=O)O',
     'elements': {'C': 5, 'H': 10, 'N': 2, 'O': 3}},
    {'name': 'Lysine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NCCCCC(N)C(=O)O',
     'elements': {'C': 6, 'H': 14, 'N': 2, 'O': 2}},
    {'name': 'Arginine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'N=C(N)NCCCC(N)C(=O)O',
     'elements': {'C': 6, 'H': 14, 'N': 4, 'O': 2}},
    {'name': 'Histidine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(Cc1c[nH]cn1)C(=O)O',
     'elements': {'C': 6, 'H': 9, 'N': 3, 'O': 2}},
    {'name': 'Phenylalanine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(Cc1ccccc1)C(=O)O',
     'elements': {'C': 9, 'H': 11, 'N': 1, 'O': 2}},
    {'name': 'Tyrosine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(Cc1ccc(O)cc1)C(=O)O',
     'elements': {'C': 9, 'H': 11, 'N': 1, 'O': 3}},
    {'name': 'Tryptophan', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'NC(Cc1c[nH]c2ccccc12)C(=O)O',
     'elements': {'C': 11, 'H': 12, 'N': 2, 'O': 2}},
    {'name': 'Methionine', 'category': STRUCTURE_CATEGORY_ORDER[10], 'smiles': 'CSCCC(N)C(=O)O',
     'elements': {'C': 5, 'H': 11, 'N': 1, 'O': 2, 'S': 1}},
    {'name': 'Glucose', 'category': 'Sugars', 'smiles': 'OCC1OC(O)C(O)C(O)C1O', 'elements': {'C': 6, 'H': 12, 'O': 6}},
    {'name': 'Fructose', 'category': 'Sugars', 'smiles': 'OCC1(O)OCC(O)C(O)C1O', 'elements': {'C': 6, 'H': 12, 'O': 6}},
    {'name': 'Ribose', 'category': 'Sugars', 'smiles': 'OCC1OC(O)C(O)C1O', 'elements': {'C': 5, 'H': 10, 'O': 5}},
    {'name': 'Deoxyribose', 'category': 'Sugars', 'smiles': 'OCC1OC(O)CC1O', 'elements': {'C': 5, 'H': 10, 'O': 4}},
    {'name': 'Sucrose', 'category': 'Sugars', 'smiles': 'OCC1OC(OC2(CO)OC(CO)C(O)C2O)C(O)C(O)C1O',
     'elements': {'C': 12, 'H': 22, 'O': 11}},
    {'name': 'Water', 'category': STRUCTURE_CATEGORY_ORDER[11], 'smiles': 'O', 'elements': {'H': 2, 'O': 1}},
    {'name': 'Hexamethylphosphoramide', 'category': STRUCTURE_CATEGORY_ORDER[11], 'smiles': 'CN(C)P(=O)(N(C)C)N(C)C',
     'elements': {'C': 6, 'H': 18, 'N': 3, 'O': 1, 'P': 1}},
    {'name': 'Aspirin', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CC(=O)Oc1ccccc1C(=O)O',
     'elements': {'C': 9, 'H': 8, 'O': 4}},
    {'name': 'Ibuprofen', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CC(C)Cc1ccc(C(C)C(=O)O)cc1',
     'elements': {'C': 13, 'H': 18, 'O': 2}},
    {'name': 'Paracetamol', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CC(=O)Nc1ccc(O)cc1',
     'elements': {'C': 8, 'H': 9, 'N': 1, 'O': 2}},
    {'name': 'Penicillin G', 'category': STRUCTURE_CATEGORY_ORDER[12],
     'smiles': 'CC1(C)SC2C(NC(=O)Cc3ccccc3)C(=O)N2C1C(=O)O',
     'elements': {'C': 16, 'H': 18, 'N': 2, 'O': 4, 'S': 1}},
    {'name': 'Ampicillin', 'category': STRUCTURE_CATEGORY_ORDER[12],
     'smiles': 'CC1(C)SC2C(NC(=O)C(N)c3ccccc3)C(=O)N2C1C(=O)O',
     'elements': {'C': 16, 'H': 19, 'N': 3, 'O': 4, 'S': 1}},
    {'name': 'Diazepam', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CN1C(=O)CN=C(c2ccccc2)c2cc(Cl)ccc21',
     'elements': {'C': 16, 'Cl': 1, 'H': 13, 'N': 2, 'O': 1}},
    {'name': 'Morphine', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CN1CCC23c4c5ccc(O)c4OC2C(O)C=CC3C1C5',
     'elements': {'C': 17, 'H': 19, 'N': 1, 'O': 3}},
    {'name': 'Codeine', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'COc1ccc2c3c1OC1C(O)C=CC4C(C2)N(C)CCC341',
     'elements': {'C': 18, 'H': 21, 'N': 1, 'O': 3}},
    {'name': 'Sildenafil', 'category': STRUCTURE_CATEGORY_ORDER[12],
     'smiles': 'CCCc1nn(C)c2c(N3CCN(C)CC3)nc(-c3cc(S(=O)(=O)N4CCN(C)CC4)ccc3OCC)nc12',
     'elements': {'C': 27, 'H': 40, 'N': 8, 'O': 3, 'S': 1}},
    {'name': 'Atorvastatin Core', 'category': STRUCTURE_CATEGORY_ORDER[12],
     'smiles': 'CC(C)c1c(C(=O)Nc2ccccc2)c(-c2ccccc2)c(-c2ccc(F)cc2)n1CCC(O)CC(O)CC(=O)O',
     'elements': {'C': 33, 'F': 1, 'H': 35, 'N': 2, 'O': 5}},
    {'name': 'Lidocaine', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CCN(CC)CC(=O)Nc1c(C)cccc1C',
     'elements': {'C': 14, 'H': 22, 'N': 2, 'O': 1}},
    {'name': 'Procaine', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CCN(CC)CCOC(=O)c1ccc(N)cc1',
     'elements': {'C': 13, 'H': 20, 'N': 2, 'O': 2}},
    {'name': 'Fluoxetine', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CNCCC(Oc1ccc(C(F)(F)F)cc1)c1ccccc1',
     'elements': {'C': 17, 'F': 3, 'H': 18, 'N': 1, 'O': 1}},
    {'name': 'Diphenhydramine', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CN(C)CCOC(c1ccccc1)c1ccccc1',
     'elements': {'C': 17, 'H': 21, 'N': 1, 'O': 1}},
    {'name': 'Albuterol', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CC(C)(C)NCC(O)c1ccc(O)c(CO)c1',
     'elements': {'C': 13, 'H': 21, 'N': 1, 'O': 3}},
    {'name': 'Metformin', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CN(C)C(=N)NC(=N)N',
     'elements': {'C': 4, 'H': 11, 'N': 5}},
    {'name': 'Omeprazole', 'category': STRUCTURE_CATEGORY_ORDER[12],
     'smiles': 'COc1ccc2nc(S(=O)Cc3ncc(C)c(OC)c3C)nc-2cc1',
     'elements': {'C': 18, 'H': 19, 'N': 3, 'O': 3, 'S': 1}},
    {'name': 'Warfarin', 'category': STRUCTURE_CATEGORY_ORDER[12], 'smiles': 'CC(=O)CC(c1ccccc1)c1c(O)c2ccccc2oc1=O',
     'elements': {'C': 19, 'H': 16, 'O': 4}},
    {'name': 'Vitamin C (Ascorbic Acid)', 'category': STRUCTURE_CATEGORY_ORDER[13], 'smiles': 'O=C1OC(C(O)CO)C(O)=C1O',
     'elements': {'C': 6, 'H': 8, 'O': 6}},
    {'name': 'Vitamin B3 (Niacin)', 'category': STRUCTURE_CATEGORY_ORDER[13], 'smiles': 'O=C(O)c1cccnc1',
     'elements': {'C': 6, 'H': 5, 'N': 1, 'O': 2}},
    {'name': 'Vitamin B6 (Pyridoxine)', 'category': STRUCTURE_CATEGORY_ORDER[13], 'smiles': 'Cc1ncc(CO)c(CO)c1O',
     'elements': {'C': 8, 'H': 11, 'N': 1, 'O': 3}},
    {'name': 'Folic Acid', 'category': STRUCTURE_CATEGORY_ORDER[13],
     'smiles': 'Nc1nc2ncc(CNc3ccc(C(=O)NC(CCC(=O)O)C(=O)O)cc3)nc2c(=O)[nH]1',
     'elements': {'C': 19, 'H': 19, 'N': 7, 'O': 6}},
    {'name': 'Retinol (Vitamin A)', 'category': STRUCTURE_CATEGORY_ORDER[13],
     'smiles': 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/CO)C(C)(C)CCC1',
     'elements': {'C': 20, 'H': 30, 'O': 1}},
    {'name': 'Adenine', 'category': STRUCTURE_CATEGORY_ORDER[14], 'smiles': 'Nc1ncnc2[nH]cnc12',
     'elements': {'C': 5, 'H': 5, 'N': 5}},
    {'name': 'Guanine', 'category': STRUCTURE_CATEGORY_ORDER[14], 'smiles': 'Nc1nc2[nH]cnc2c(=O)[nH]1',
     'elements': {'C': 5, 'H': 5, 'N': 5, 'O': 1}},
    {'name': 'Cytosine', 'category': STRUCTURE_CATEGORY_ORDER[14], 'smiles': 'Nc1cc[nH]c(=O)n1',
     'elements': {'C': 4, 'H': 5, 'N': 3, 'O': 1}},
    {'name': 'Thymine', 'category': STRUCTURE_CATEGORY_ORDER[14], 'smiles': 'Cc1c[nH]c(=O)[nH]c1=O',
     'elements': {'C': 5, 'H': 6, 'N': 2, 'O': 2}},
    {'name': 'Uracil', 'category': STRUCTURE_CATEGORY_ORDER[14], 'smiles': 'O=c1cc[nH]c(=O)[nH]1',
     'elements': {'C': 4, 'H': 4, 'N': 2, 'O': 2}},
    {'name': 'Tetrafluoroethylene (PTFE)', 'category': STRUCTURE_CATEGORY_ORDER[15], 'smiles': 'FC(F)=C(F)F',
     'elements': {'C': 2, 'F': 4}},
    {'name': 'Caprolactam (Nylon 6)', 'category': STRUCTURE_CATEGORY_ORDER[15], 'smiles': 'O=C1CCCCCN1',
     'elements': {'C': 6, 'H': 11, 'N': 1, 'O': 1}},
    {'name': 'Adipic Acid (Nylon 66)', 'category': STRUCTURE_CATEGORY_ORDER[15], 'smiles': 'O=C(O)CCCCC(=O)O',
     'elements': {'C': 6, 'H': 10, 'O': 4}},
    {'name': 'Terephthalic Acid (PET)', 'category': STRUCTURE_CATEGORY_ORDER[15], 'smiles': 'O=C(O)c1ccc(C(=O)O)cc1',
     'elements': {'C': 8, 'H': 6, 'O': 4}},
    {'name': 'Bisphenol A (Polycarbonate)', 'category': STRUCTURE_CATEGORY_ORDER[15],
     'smiles': 'CC(C)(c1ccc(O)cc1)c1ccc(O)cc1',
     'elements': {'C': 15, 'H': 16, 'O': 2}},
    {'name': 'Carbon Dioxide', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'O=C=O',
     'elements': {'C': 1, 'O': 2}},
    {'name': 'Carbon Monoxide', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': '[C-]#[O+]',
     'elements': {'C': 1, 'O': 1}},
    {'name': 'Ammonia', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'N', 'elements': {'H': 3, 'N': 1}},
    {'name': 'Hydrogen Peroxide', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'OO',
     'elements': {'H': 2, 'O': 2}},
    {'name': 'Nitric Acid', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'O=[N+]([O-])O',
     'elements': {'H': 1, 'N': 1, 'O': 3}},
    {'name': 'Sulfuric Acid', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'O=S(=O)(O)O',
     'elements': {'H': 2, 'O': 4, 'S': 1}},
    {'name': 'Phosphoric Acid', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'O=P(O)(O)O',
     'elements': {'H': 3, 'O': 4, 'P': 1}},
    {'name': 'Hydrogen Cyanide', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'C#N',
     'elements': {'C': 1, 'H': 1, 'N': 1}},
    {'name': 'Ozone', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'O=[O+][O-]', 'elements': {'O': 3}},
    {'name': 'Nitrous Oxide', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': '[N-]=[N+]=O',
     'elements': {'N': 2, 'O': 1}},
    {'name': 'Sulfur Dioxide', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'O=S=O',
     'elements': {'O': 2, 'S': 1}},
    {'name': 'Boric Acid', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'OB(O)O',
     'elements': {'B': 1, 'H': 3, 'O': 3}},
    {'name': 'Silicic Acid', 'category': STRUCTURE_CATEGORY_ORDER[16], 'smiles': 'O[Si](O)(O)O',
     'elements': {'H': 4, 'O': 4, 'Si': 1}},
    {'name': 'Caproic Acid', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'CCCCCC(=O)O',
     'elements': {'C': 6, 'H': 12, 'O': 2}},
    {'name': 'Caprylic Acid', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'CCCCCCCC(=O)O',
     'elements': {'C': 8, 'H': 16, 'O': 2}},
    {'name': 'Capric Acid', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'CCCCCCCCCC(=O)O',
     'elements': {'C': 10, 'H': 20, 'O': 2}},
    {'name': 'Lauric Acid', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'CCCCCCCCCCCC(=O)O',
     'elements': {'C': 12, 'H': 24, 'O': 2}},
    {'name': 'Myristic Acid', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'CCCCCCCCCCCCCC(=O)O',
     'elements': {'C': 14, 'H': 28, 'O': 2}},
    {'name': 'Palmitic Acid', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'CCCCCCCCCCCCCCCC(=O)O',
     'elements': {'C': 16, 'H': 32, 'O': 2}},
    {'name': 'Stearic Acid', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'CCCCCCCCCCCCCCCCCC(=O)O',
     'elements': {'C': 18, 'H': 36, 'O': 2}},
    {'name': 'Oleic Acid', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'CCCCCCCC/C=C\\CCCCCCCC(=O)O',
     'elements': {'C': 18, 'H': 34, 'O': 2}},
    {'name': 'Linoleic Acid', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'CCCCC/C=C\\C/C=C\\CCCCCCCC(=O)O',
     'elements': {'C': 18, 'H': 32, 'O': 2}},
    {'name': 'Linolenic Acid', 'category': STRUCTURE_CATEGORY_ORDER[17],
     'smiles': 'CC/C=C\\C/C=C\\C/C=C\\CCCCCCCC(=O)O',
     'elements': {'C': 18, 'H': 30, 'O': 2}},
    {'name': 'Arachidonic Acid', 'category': STRUCTURE_CATEGORY_ORDER[17],
     'smiles': 'CCCCC/C=C\\C/C=C\\C/C=C\\C/C=C\\CCCC(=O)O', 'elements': {'C': 20, 'H': 32, 'O': 2}},
    {'name': 'Glyceryl Tristearate', 'category': STRUCTURE_CATEGORY_ORDER[17],
     'smiles': 'CCCCCCCCCCCCCCCCCC(=O)OCC(COC(=O)CCCCCCCCCCCCCCCCC)OC(=O)CCCCCCCCCCCCCCCCC',
     'elements': {'C': 57, 'H': 110, 'O': 6}},
    {'name': 'Cholesterol', 'category': STRUCTURE_CATEGORY_ORDER[17],
     'smiles': 'CC(C)CCCC(C)C1CCC2C3CC=C4CC(O)CCC4(C)C3CCC12C', 'elements': {'C': 27, 'H': 46, 'O': 1}},
    {'name': 'Lecithin Head (Choline)', 'category': STRUCTURE_CATEGORY_ORDER[17], 'smiles': 'C[N+](C)(C)CCO',
     'elements': {'C': 5, 'H': 14, 'N': 1, 'O': 1}},
    {'name': 'Limonene', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'C=C(C)C1CC=C(C)CC1',
     'elements': {'C': 10, 'H': 16}},
    {'name': 'Menthol', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'CC1CCC(C(C)C)C(O)C1',
     'elements': {'C': 10, 'H': 20, 'O': 1}},
    {'name': 'Camphor', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'CC12CCC(CC1=O)C2(C)C',
     'elements': {'C': 10, 'H': 16, 'O': 1}},
    {'name': 'Pinene', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'CC1=CCC2CC1C2(C)C',
     'elements': {'C': 10, 'H': 16}},
    {'name': 'Geraniol', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'CC(C)=CCCC(C)=CCO',
     'elements': {'C': 10, 'H': 18, 'O': 1}},
    {'name': 'Citral', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'CC(C)=CCCC(C)=CC=O',
     'elements': {'C': 10, 'H': 16, 'O': 1}},
    {'name': 'Eugenol', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'C=CCc1ccc(O)c(OC)c1',
     'elements': {'C': 10, 'H': 12, 'O': 2}},
    {'name': 'Vanillin', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'COc1cc(C=O)ccc1O',
     'elements': {'C': 8, 'H': 8, 'O': 3}},
    {'name': 'Thymol', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'Cc1ccc(C(C)C)c(O)c1',
     'elements': {'C': 10, 'H': 14, 'O': 1}},
    {'name': 'Carvone', 'category': STRUCTURE_CATEGORY_ORDER[18], 'smiles': 'C=C(C)C1CC=C(C)C(=O)C1',
     'elements': {'C': 10, 'H': 14, 'O': 1}},
    {'name': 'Squalene', 'category': STRUCTURE_CATEGORY_ORDER[18],
     'smiles': 'CC(C)=CCCC(C)=CCCC(C)=CCCC=C(C)CCC=C(C)CCC=C(C)C', 'elements': {'C': 30, 'H': 50}},
    {'name': 'Beta-Carotene', 'category': STRUCTURE_CATEGORY_ORDER[18],
     'smiles': 'CC1=C(/C=C/C(C)=C/C=C/C(C)=C/C=C/C=C(C)/C=C/C=C(C)/C=C/C2=C(C)CCCC2(C)C)C(C)(C)CCC1',
     'elements': {'C': 40, 'H': 56}},
    {'name': 'Testosterone', 'category': STRUCTURE_CATEGORY_ORDER[19],
     'smiles': 'CC12CCC(=O)C=C1CCC1C2CCC2(C)C(O)CCC12',
     'elements': {'C': 19, 'H': 28, 'O': 2}},
    {'name': 'Progesterone', 'category': STRUCTURE_CATEGORY_ORDER[19],
     'smiles': 'CC(=O)C1CCC2C3CCC4(C)C(=O)CCC4C3CCC12C',
     'elements': {'C': 20, 'H': 30, 'O': 2}},
    {'name': 'Estradiol', 'category': STRUCTURE_CATEGORY_ORDER[19], 'smiles': 'CC12CCC3c4ccc(O)cc4CCC3C1CCC2O',
     'elements': {'C': 18, 'H': 24, 'O': 2}},
    {'name': 'Cortisone', 'category': STRUCTURE_CATEGORY_ORDER[19],
     'smiles': 'CC12C=CC(=O)C=C1CCC1C2C(=O)CC2(C)C1CCC2(O)C(=O)CO',
     'elements': {'C': 21, 'H': 26, 'O': 5}},
    {'name': 'Indigo', 'category': STRUCTURE_CATEGORY_ORDER[20], 'smiles': 'O=C1Nc2ccccc2/C1=C1\\C(=O)Nc2ccccc21',
     'elements': {'C': 16, 'H': 10, 'N': 2, 'O': 2}},
    {'name': 'Azobenzene', 'category': STRUCTURE_CATEGORY_ORDER[20], 'smiles': 'c1ccc(/N=N/c2ccccc2)cc1',
     'elements': {'C': 12, 'H': 10, 'N': 2}},
    {'name': 'Phenolphthalein', 'category': STRUCTURE_CATEGORY_ORDER[20], 'smiles': 'O=C1OC(O)(c2ccc(O)cc2)c2ccccc21',
     'elements': {'C': 14, 'H': 10, 'O': 4}},
    {'name': 'Anthraquinone', 'category': STRUCTURE_CATEGORY_ORDER[20], 'smiles': 'O=C1c2ccccc2C(=O)c2ccccc21',
     'elements': {'C': 14, 'H': 8, 'O': 2}},
    {'name': 'Fluorescein', 'category': STRUCTURE_CATEGORY_ORDER[20],
     'smiles': 'O=C1OC2(c3ccc(O)cc3Oc3cc(O)ccc32)c2ccccc21',
     'elements': {'C': 20, 'H': 12, 'O': 5}},
    {'name': '18-Crown-6', 'category': STRUCTURE_CATEGORY_ORDER[21], 'smiles': 'C1COCCOCCOCCOCCO1',
     'elements': {'C': 10, 'H': 20, 'O': 5}},
    {'name': '12-Crown-4', 'category': STRUCTURE_CATEGORY_ORDER[21], 'smiles': 'C1COCCOCCO1',
     'elements': {'C': 6, 'H': 12, 'O': 3}},
    {'name': 'Quinoxaline', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2nccnc2c1',
     'elements': {'C': 8, 'H': 6, 'N': 2}},
    {'name': 'Phthalazine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2cnncc2c1',
     'elements': {'C': 8, 'H': 6, 'N': 2}},
    {'name': 'Carbazole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2c(c1)[nH]c1ccccc12',
     'elements': {'C': 12, 'H': 9, 'N': 1}},
    {'name': 'Acridine', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2nc3ccccc3cc2c1',
     'elements': {'C': 13, 'H': 9, 'N': 1}},
    {'name': 'Xanthene', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1ccc2c(c1)Cc1ccccc1O2',
     'elements': {'C': 13, 'H': 10, 'O': 1}},
    {'name': 'Triazole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1cn[nH]n1',
     'elements': {'C': 2, 'H': 3, 'N': 3}},
    {'name': 'Tetrazole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1nnn[nH]1',
     'elements': {'C': 1, 'H': 2, 'N': 4}},
    {'name': 'Isoxazole', 'category': STRUCTURE_CATEGORY_ORDER[4], 'smiles': 'c1cnoc1',
     'elements': {'C': 3, 'H': 3, 'N': 1, 'O': 1}},
    {'name': 'Ethyl Butyrate', 'category': STRUCTURE_CATEGORY_ORDER[22], 'smiles': 'CCCC(=O)OCC',
     'elements': {'C': 6, 'H': 12, 'O': 2}},
    {'name': 'Isoamyl Acetate', 'category': STRUCTURE_CATEGORY_ORDER[22], 'smiles': 'CC(=O)OCCC(C)C',
     'elements': {'C': 7, 'H': 14, 'O': 2}},
    {'name': 'Benzyl Acetate', 'category': STRUCTURE_CATEGORY_ORDER[22], 'smiles': 'CC(=O)OCc1ccccc1',
     'elements': {'C': 9, 'H': 10, 'O': 2}},
    {'name': 'Methyl Salicylate', 'category': STRUCTURE_CATEGORY_ORDER[22], 'smiles': 'COC(=O)c1ccccc1O',
     'elements': {'C': 8, 'H': 8, 'O': 3}},
    {'name': 'Ethyl Cinnamate', 'category': STRUCTURE_CATEGORY_ORDER[22], 'smiles': 'CCOC(=O)/C=C/c1ccccc1',
     'elements': {'C': 11, 'H': 12, 'O': 2}},
    {'name': 'Geranyl Acetate', 'category': STRUCTURE_CATEGORY_ORDER[22], 'smiles': 'CC(=O)OCC=C(C)CCC=C(C)C',
     'elements': {'C': 12, 'H': 20, 'O': 2}},
    {'name': 'Linalyl Acetate', 'category': STRUCTURE_CATEGORY_ORDER[22], 'smiles': 'C=CC(C)(CCC=C(C)C)OC(C)=O',
     'elements': {'C': 12, 'H': 20, 'O': 2}},
    {'name': 'n-Undecane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCCCCCCCC',
     'elements': {'C': 11, 'H': 24}},
    {'name': 'n-Tridecane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCCCCCCCCCC',
     'elements': {'C': 13, 'H': 28}},
    {'name': 'n-Tetradecane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCCCCCCCCCCCCC',
     'elements': {'C': 14, 'H': 30}},
    {'name': '2,3-Dimethylbutane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CC(C)C(C)C',
     'elements': {'C': 6, 'H': 14}},
    {'name': '3-Ethylpentane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'CCC(CC)CC',
     'elements': {'C': 7, 'H': 16}},
    {'name': 'Spiropentane', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CC12CC2',
     'elements': {'C': 5, 'H': 8}},
    {'name': 'Bicyclohexyl', 'category': STRUCTURE_CATEGORY_ORDER[1], 'smiles': 'C1CCC(C2CCCCC2)CC1',
     'elements': {'C': 12, 'H': 22}},
    {'name': '2-Methyl-1-Butene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=C(C)CC',
     'elements': {'C': 5, 'H': 10}},
    {'name': '3-Methyl-1-Butene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CC(C)C',
     'elements': {'C': 5, 'H': 10}},
    {'name': '1-Heptene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CCCCCC', 'elements': {'C': 7, 'H': 14}},
    {'name': '1-Octene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CCCCCCC', 'elements': {'C': 8, 'H': 16}},
    {'name': 'Allene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=C=C', 'elements': {'C': 3, 'H': 4}},
    {'name': '1,5-Hexadiene', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C=CCCC=C',
     'elements': {'C': 6, 'H': 10}},
    {'name': '1-Pentyne', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C#CCCC', 'elements': {'C': 5, 'H': 8}},
    {'name': '2-Pentyne', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'CC#CCC', 'elements': {'C': 5, 'H': 8}},
    {'name': '1-Hexyne', 'category': STRUCTURE_CATEGORY_ORDER[2], 'smiles': 'C#CCCCC', 'elements': {'C': 6, 'H': 10}},
    {'name': 'Mesitylene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Cc1cc(C)cc(C)c1',
     'elements': {'C': 9, 'H': 12}},
    {'name': 'Durene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Cc1ccc(C)c(C)c1C',
     'elements': {'C': 10, 'H': 14}},
    {'name': '4-Tert-Butyltoluene', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Cc1ccc(C(C)(C)C)cc1',
     'elements': {'C': 11, 'H': 16}},
    {'name': 'Diphenylmethane', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'c1ccc(Cc2ccccc2)cc1',
     'elements': {'C': 13, 'H': 12}},
    {'name': 'Triphenylmethane', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'c1ccc(C(c2ccccc2)c2ccccc2)cc1',
     'elements': {'C': 19, 'H': 16}},
    {'name': '2-Naphthol', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Oc1ccc2ccccc2c1',
     'elements': {'C': 10, 'H': 8, 'O': 1}},
    {'name': '1-Naphthylamine', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Nc1cccc2ccccc12',
     'elements': {'C': 10, 'H': 9, 'N': 1}},
    {'name': 'p-Toluidine', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Cc1ccc(N)cc1',
     'elements': {'C': 7, 'H': 9, 'N': 1}},
    {'name': 'p-Phenylenediamine', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Nc1ccc(N)cc1',
     'elements': {'C': 6, 'H': 8, 'N': 2}},
    {'name': '4-Aminobenzoic Acid', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Nc1ccc(C(=O)O)cc1',
     'elements': {'C': 7, 'H': 7, 'N': 1, 'O': 2}},
    {'name': 'Sulfanilamide', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'Nc1ccc(S(N)(=O)=O)cc1',
     'elements': {'C': 6, 'H': 8, 'N': 2, 'O': 2, 'S': 1}},
    {'name': 'Saccharin', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'O=C1NS(=O)(=O)c2ccccc21',
     'elements': {'C': 7, 'H': 5, 'N': 1, 'O': 3, 'S': 1}},
    {'name': 'Benzenesulfonic Acid', 'category': STRUCTURE_CATEGORY_ORDER[3], 'smiles': 'O=S(=O)(O)c1ccccc1',
     'elements': {'C': 6, 'H': 6, 'O': 3, 'S': 1}},
]
